name: DeepIsaHOL
channels:
  - conda-forge
dependencies:
  - matplotlib
  - py4j
  - python=3.11
  - pip:
    - Jinja2==3.1.4
    - Markdown==3.8.2
    - MarkupSafe==2.1.5
    - PyYAML==6.0.2
    - Pygments==2.19.2
    - Werkzeug==3.1.3
    - absl-py==2.3.1
    - accelerate==1.9.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.15
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - attrs==25.3.0
    - bitsandbytes==0.46.1
    - certifi==2025.8.3
    - charset-normalizer==3.4.2
    - cut-cross-entropy==25.1.1
    - datasets==3.6.0
    - dill==0.3.8
    - docstring_parser==0.17.0
    - filelock==3.13.1
    - frozenlist==1.7.0
    - fsspec==2024.6.1
    - gguf==0.17.1
    - grpcio==1.74.0
    - hf-xet==1.1.5
    - hf_transfer==0.1.9
    - huggingface-hub==0.34.3
    - idna==3.10
    - jsonschema==4.25.1
    - jsonschema-specifications==2025.4.1
    - markdown-it-py==3.0.0
    - mdurl==0.1.2
    - mistral_common==1.8.4
    - mpmath==1.3.0
    - msgspec==0.19.0
    - multidict==6.6.3
    - multiprocess==0.70.16
    - networkx==3.3
    - nvidia-cublas-cu12==12.8.3.14
    - nvidia-cuda-cupti-cu12==12.8.57
    - nvidia-cuda-nvrtc-cu12==12.8.61
    - nvidia-cuda-runtime-cu12==12.8.57
    - nvidia-cudnn-cu12==9.7.1.26
    - nvidia-cufft-cu12==11.3.3.41
    - nvidia-cufile-cu12==1.13.0.11
    - nvidia-curand-cu12==10.3.9.55
    - nvidia-cusolver-cu12==11.7.2.55
    - nvidia-cusparse-cu12==12.5.7.53
    - nvidia-cusparselt-cu12==0.6.3
    - nvidia-nccl-cu12==2.26.2
    - nvidia-nvjitlink-cu12==12.8.61
    - nvidia-nvtx-cu12==12.8.55
    - pandas==2.3.1
    - peft==0.17.0
    - propcache==0.3.2
    - protobuf==6.31.1
    - psutil==7.0.0
    - pyarrow==21.0.0
    - pycountry==24.6.1
    - pydantic==2.11.7
    - pydantic-extra-types==2.10.5
    - pydantic_core==2.33.2
    - pytz==2025.2
    - referencing==0.36.2
    - regex==2025.7.34
    - requests==2.32.4
    - rich==14.1.0
    - rpds-py==0.27.1
    - safetensors==0.5.3
    - sentencepiece==0.2.0
    - shtab==1.7.2
    - sympy==1.13.3
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - tiktoken==0.11.0
    - timm==1.0.19
    - tokenizers==0.21.4
    - torch==2.7.1+cu128
    - torchaudio==2.7.1+cu128
    - torchvision==0.22.1+cu128
    - tqdm==4.67.1
    - transformers==4.54.1
    - triton==3.3.1
    - trl==0.20.0
    - typeguard==4.4.4
    - typing-inspection==0.4.1
    - typing_extensions==4.14.1
    - tyro==0.9.27
    - tzdata==2025.2
    - unsloth==2025.8.1
    - unsloth_zoo==2025.8.1
    - urllib3==2.5.0
    - xformers==0.0.31.post1
    - xxhash==3.5.0
    - yarl==1.20.1
